spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 30s
  # jackson 설정은 spring 바로 아래로 이동
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://127.0.0.1:3306/Glemoa
    username: root
    password: yourpassword
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

glemoa:
  batch-size: 100
  crawlers:
    - name: arcaLiveCrawler
      cron: "0 */5 * * * *" # cron 분마다 크롤링
      lookback-minutes: 1440 # cron 분 마다 게시글을 업데이트 및 둘러보는 시간
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: bobaedreamCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: clienCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: dcInsideCrawler
      cron: "0 */5 * * * *"  # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: etolandCrawler
      cron: "0 */5 * * * *"    # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: fmkoreaCrawler
      cron: "0 */5 * * * *"  # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: humorunivCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: invenCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: mlbparkCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: natePannCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: ppomppuCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: ruliwebCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true
    - name: theqooCrawler
      cron: "0 */5 * * * *"  # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 7
      restart-crawl-minutes: 1440
      enabled: true

logging:
  config: classpath:logback-local.xml
  level:
    # 기본 레벨을 INFO로 유지 (기타 라이브러리)
    root: INFO