server.port: 8080

spring:
  application:
    name: collector-service
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://127.0.0.1:3306/Glemoa
    username: root
    password: yourpassword
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

#crawler:
#  initial-pages:
#    ppomppu: 3
#    fmkorea: 3
#    dcinside: 3
#    clien: 3
#    ruliweb: 3
#    theqoo: 3
#    etoland: 3
#    humoruniv: 3
#    bobaedream: 3
#    mlbpark: 3
#    arcalive: 3
#    inven: 3
#    natepann: 3
#    ppomppu: 30
#    fmkorea: 30
#    dcinside: 30
#    clien: 30
#    ruliweb: 30
#    theqoo: 30
#    etoland: 30
#    humoruniv: 30
#    bobaedream: 30
#    mlbpark: 30
#    arcalive: 30
#    inven: 30
#    natepann: 30
#    inven: 3
#    natepann: 3

glemoa:
  scheduler:
    # fixed-delay-seconds: 60 # 더 이상 사용되지 않음
    initial-crawl-days: 1 # 최초 실행 시 수집할 기간 (일)
#    scheduled-crawl-minutes: 30 # 스케줄링 실행 시 수집할 시간 (분)
  batch-size: 100
  crawlers:
    - name: arcaLiveCrawler
      cron: "0 */15 * * * *" # 15분마다
      enabled: true
    - name: bobaedreamCrawler
      cron: "0 */20 * * * *" # 20분마다
      enabled: true
    - name: clienCrawler
      cron: "0 */10 * * * *" # 10분마다
      enabled: true
    - name: dcInsideCrawler
      cron: "0 */1 * * * *"  # 1분마다
      enabled: true
    - name: etolandCrawler
      cron: "0 0 * * * *"    # 매시 정각
      enabled: true
    - name: fmkoreaCrawler
      cron: "0 */5 * * * *"  # 5분마다
      enabled: true
    - name: humorunivCrawler
      cron: "0 */30 * * * *" # 30분마다
      enabled: true
    - name: invenCrawler
      cron: "0 */10 * * * *" # 10분마다
      enabled: true
    - name: mlbparkCrawler
      cron: "0 */15 * * * *" # 15분마다
      enabled: true
    - name: natePannCrawler
      cron: "0 */20 * * * *" # 20분마다
      enabled: true
    - name: ppomppuCrawler
      cron: "0 */10 * * * *" # 10분마다
      enabled: true
    - name: ruliwebCrawler
      cron: "0 */10 * * * *" # 10분마다
      enabled: true
    - name: theqooCrawler
      cron: "0 */5 * * * *"  # 5분마다
      enabled: true

