server.port: 8080

spring:
  application:
    name: collector-service
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://127.0.0.1:3306/Glemoa
    username: root
    password: yourpassword
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

#crawler:
#  initial-pages:
#    ppomppu: 3
#    fmkorea: 3
#    dcinside: 3
#    clien: 3
#    ruliweb: 3
#    theqoo: 3
#    etoland: 3
#    humoruniv: 3
#    bobaedream: 3
#    mlbpark: 3
#    arcalive: 3
#    inven: 3
#    natepann: 3
#    ppomppu: 30
#    fmkorea: 30
#    dcinside: 30
#    clien: 30
#    ruliweb: 30
#    theqoo: 30
#    etoland: 30
#    humoruniv: 30
#    bobaedream: 30
#    mlbpark: 30
#    arcalive: 30
#    inven: 30
#    natepann: 30
#    inven: 3
#    natepann: 3

glemoa:
  scheduler:
    fixed-delay-seconds: 60 # 스케줄러 실행 완료 후 대기 시간 (초)
    initial-crawl-days: 1 # 최초 실행 시 수집할 기간 (일)
    scheduled-crawl-minutes: 30 # 스케줄링 실행 시 수집할 시간 (분)
